### PR TITLE
Add specs

### LINKED ISSUE #1: Tests
No idea how I would test this, but should be possible. Would really appreciate some help on this.

### PR DESCRIPTION
**Pull request by steelbrain**
Using the CI script from https://github.com/atom/ci

You can run these specs by running `apm test` in the package root.
#### Explanation for removing scroll logic

Atom does it by itself.

Fixes #1

[Review on Reviewable](https://reviewable.io/reviews/sindresorhus/atom-set-text/2)

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Atom does it by itself.

It does, but not perfectly. If the cursor is out of the view it will scroll to the cursor. This code locks the scrolling in one place regardless. It was originally added in https://github.com/sindresorhus/atom-esformatter/pull/13 by @adros.

**Comment by steelbrain** [comment]
@sindresorhus Thank you for correcting me. I'll revert the removal

**Comment by steelbrain** [comment]
@sindresorhus Updated

**Comment by sindresorhus** [comment]
Awesome! Thanks again :)

**Pull request closed without merging**
